# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 签到

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' #北京时间0点运行，action会有延迟
  watch:
    types: started
  repository_dispatch:
    types: jd_scripts
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          npm install
      - name: '运行 【多功能签到】'
        run: |
          node other/lightning_checkin.js
          node other/j.mr_checkin.js
          node other/v2ex_checkin.js
          node other/smzdm_checkin.js
          node other/bcs_checkin.js
          node other/52pojie_checkin.js
        env:
          FREE_MY_CLOUD_USERNAME: ${{ secrets.FREE_MY_CLOUD_USERNAME }}
          FREE_MY_CLOUD_PASSWORD: ${{ secrets.FREE_MY_CLOUD_PASSWORD }}
          JJ_USERNAME: ${{ secrets.JJ_USERNAME }}
          JJ_PASSWORD: ${{ secrets.JJ_PASSWORD }}
          V2EX_COOKIE: ${{ secrets.V2EX_COOKIE }}
          SMZDM_COOKIE: ${{ secrets.SMZDM_COOKIE }}
          BCS_COOKIE: ${{ secrets.BCS_COOKIE }}
          POJIE52_COOKIE: ${{ secrets.POJIE52_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
